## 30 practical data-cleaning questions

### Basic Cleaning

#### 1. Load the CSV file using Pandas and display the first 10 rows.

In [75]:
import pandas  as pd 

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\messy_customer_loan_dataset.csv")

df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
5,CUST100925,32.0,317590.0,690.0,Salaried,Graduate,M,Mumbai,Premium,Auto,235549.0,120,5.0,0.46,No
6,CUST100758,39.0,322966.0,707.0,Contract,Graduate,Married,Chennai,Mass,Personal,563319.0,24,7.0,0.323,No
7,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
8,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
9,CUST101198,67.0,1063307.0,774.0,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693.0,120,2.0,0.394,Yes

#### 2. Display the number of rows and columns in the dataset.

In [76]:
df.shape

(1535, 15)

#### 3. Display all column names and identify which column names have leading/trailing spaces.

In [77]:
df.columns

Index([' Customer ID ', 'Age ', 'Annual Income', 'credit Score ',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment ', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits ', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

#### 4. Clean all column names by removing extra spaces and converting them into a consistent format such as snake_case.

In [78]:
df.columns = (
    df.columns
      .str.strip()                      
      .str.lower()                     
      .str.replace(' ', '_')            
      .str.replace(r'[^\w]', '', regex=True)  
)

df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score', 'employmenttype',
       'education__level', 'marital_status', 'city', 'customer_segment',
       'loan_type', 'loan_amount_inr', 'tenure_months', 'monthly_visits',
       'debt_to_income', 'loan_approved'],
      dtype='object')

#### 5. Check the data type of every column.

In [79]:
df.dtypes

customer_id         object
age                 object
annual_income       object
credit_score        object
employmenttype      object
education__level    object
marital_status      object
city                object
customer_segment    object
loan_type           object
loan_amount_inr     object
tenure_months        int64
monthly_visits      object
debt_to_income      object
loan_approved       object
dtype: object

#### 6. Find the total number of missing values in each column.

In [80]:
df.isnull().sum()

customer_id           0
age                  71
annual_income        84
credit_score         77
employmenttype       60
education__level     46
marital_status        0
city                 52
customer_segment      0
loan_type             0
loan_amount_inr     102
tenure_months         0
monthly_visits       55
debt_to_income       89
loan_approved         0
dtype: int64

#### 7. Find the percentage of missing values in each column.

In [81]:
df.isnull().mean()*100

customer_id         0.000000
age                 4.625407
annual_income       5.472313
credit_score        5.016287
employmenttype      3.908795
education__level    2.996743
marital_status      0.000000
city                3.387622
customer_segment    0.000000
loan_type           0.000000
loan_amount_inr     6.644951
tenure_months       0.000000
monthly_visits      3.583062
debt_to_income      5.798046
loan_approved       0.000000
dtype: float64

#### 8. Find all rows where Age is missing.

In [82]:
missing_age = df[df['age'].isnull()]

missing_age

,customer_id,age,annual_income,credit_score,employmenttype,education__level,marital_status,city,customer_segment,loan_type,loan_amount_inr,tenure_months,monthly_visits,debt_to_income,loan_approved
21,CUST100354,NaN,302606.0,726.0,NaN,Graduate,Single,Bengaluru,Mass,Auto,269320.0,84,6.0,0.353,No
29,CUST100989,NaN,650000 INR,778.0,Self-Employed,Graduate,Divorced,Pune,unknown,Home,1083921.0,48,5.0,0.4x,No
100,CUST101150,NaN,100,723.0,Self-Employed,12th,Married,NaN,Mass,Education,454937.0,48,five,0.303,Yes
108,CUST100535,NaN,458878.0,782.0,Salaried,Diploma,Married,Mumbai,Mass,Auto,549385.0,36,7.0,0.279,No
113,CUST101055,NaN,1112464.0,120,Salaried,Diploma,Married,Kolkata,Mass,Auto,427759.0,84,3.0,0.102,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,CUST100392,NaN,570532.0,766.0,Contract,Postgraduate,Married,Jaipur,Mass,Home,937612.0,36,3.0,0.51,Yes
1430,CUST101368,NaN,519228.0,728.0,Business,Postgraduate,Married,Hyderabad,Mass,Home,514679.0,12,4.0,0.392,Yes
1498,CUST100700,NaN,658802.0,772.0,Contract,Postgraduate,Married,Mumbai,Mass,Auto,257699.0,24,4.0,0.584,Yes
1503,CUST100748,NaN,338339.0,673.0,Business,Graduate,Married,Chennai,Premium,Business,223704.0,12,7.0,0.02,No
1516,CUST100770,NaN,708229.0,801.0,Business,NaN,Single,Chennai,Premium,Personal,341664.0,120,5.0,0.651,Yes

#### 9. Find all rows where Annual Income is missing.

In [83]:
missing_income = df[df['annual_income'].isnull()]

missing_income

,customer_id,age,annual_income,credit_score,employmenttype,education__level,marital_status,city,customer_segment,loan_type,loan_amount_inr,tenure_months,monthly_visits,debt_to_income,loan_approved
41,CUST101081,64.0,NaN,749.0,Self-Employed,Diploma,Single,Kolkata,Premium,Personal,254754.0,24,5.0,0.327,No
103,CUST101403,35.0,NaN,660.0,Self-Employed,Graduate,Married,Delhi,Affluent,Home,NaN,36,4.0,0.402,No
119,CUST101095,36.0,NaN,782.0,self-employed,Postgraduate,Married,Bengaluru,Affluent,Home,225725.0,60,5.0,0.341,Yes
132,CUST101048,49.0,NaN,713.0,Salaried,Postgraduate,Single,Bengaluru,Affluent,auto,301697.0,48,7.0,0.35,Yes
144,CUST100530,64.0,NaN,761.0,Business,Diploma,Single,NaN,Affluent,Business,1182185.0,120,7.0,0.02,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,CUST100776,65.0,NaN,667.0,Self-Employed,GRADUATE,Single,Mumbai,Mass,Personal,995167.0,72,3.0,0.6,Yes
1493,CUST101496,41.0,NaN,662.0,Self-Employed,12th,Single,Kolkata,Affluent,Education,693422.0,48,5.0,0.272,No
1501,CUST100475,50.0,NaN,802.0,Contract,12th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

#### 10.Remove completely duplicate rows and report how many duplicate rows were removed.

In [84]:
duplicate_count = df.duplicated().sum()

In [86]:
df.drop_duplicates(inplace=True)

print("Number of duplicate rows removed:", duplicate_count)

Number of duplicate rows removed: 35

### Data Type & Invalid Values

#### 11.The Age column contains numbers as well as values like "unknown" and "twenty five". Clean this column and convert it into a proper numeric column.

In [87]:
import numpy as np
import pandas as pd

df['age'] = df['age'].replace({
    'unknown': np.nan,
    'twenty five': 25
})

df['age'] = pd.to_numeric(df['age'], errors='coerce')

print(df['age'])
print(df['age'].dtype)

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: float64
float64

#### 12.The Annual Income column contains values such as 650000 INR, ₹720000, 1.2L, and N/A. Clean the column and convert the valid values into numeric format.

In [89]:
import numpy as np
import pandas as pd

df['annual_income'] = (
    df['annual_income']
      .astype(str)
      .str.replace('INR', '', regex=False)   # Remove INR
      .str.replace('₹', '', regex=False)     # Remove ₹
      .str.strip()
)

df['annual_income'] = df['annual_income'].replace(
    r'(\d+\.?\d*)L',
    lambda x: str(float(x.group(1)) * 100000),
    regex=True
)

df['annual_income'] = df['annual_income'].replace('N/A', np.nan)

df['annual_income'] = pd.to_numeric(df['annual_income'], errors='coerce')

print(df['annual_income'])
print(df['annual_income'].dtype)

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532          NaN
1533     543340.0
1534          NaN
Name: annual_income, Length: 1500, dtype: float64
float64

#### 13.Clean the Credit Score column and identify values that cannot be converted into numbers.

In [94]:
# Save original values
original = df['credit_score'].copy()

# Convert to numeric
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')

# Show invalid original values
invalid_values = original[df['credit_score'].isna()]

print(invalid_values)

23     NaN
37     NaN
47     NaN
73     NaN
84     NaN
        ..
1495   NaN
1499   NaN
1502   NaN
1511   NaN
1529   NaN
Name: credit_score, Length: 96, dtype: float64

#### 14.The Loan Amount column contains currency symbols, text, and numeric values. Remove the unwanted characters and convert it into numeric format.