#### 1. Load the CSV using Pandas and display the first 10 rows.

In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\customer_data.csv")

df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.283473578603065,44108.07924936186,793.2135772820182,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.630009830989785,80888.86263734727,850.0,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.520166822399105,50011.55555812526,796.7940989517157,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30823662701,482.3950728788773,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

#### 2. Check the number of rows and columns in the dataset.

In [5]:
df.shape

(2000, 15)

#### 3. Display all column names and identify which column names contain
#### leading/trailing spaces or inconsistent capitalization.

In [8]:
df.columns = df.columns.str.title()

df.head()

,Customer Id,Age,Income_Usd,Credit Score,Tenure_Years,Monthly_Visits,Satisfaction,City,Customer_Segment,Gender,Is_Active,Churn_Flag,Signup_Date,Lead_Source,Notes_Text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

#### 4. Check the data type of every column using Pandas.

In [12]:
df.dtypes

Customer Id          object
Age                  object
Income_Usd           object
Credit Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

#### 5. Calculate the number and percentage of missing values in every column.

In [16]:
Miss_Value = df.isnull().sum()
Miss_Per = Miss_Value/len(df)*100

Miss_Per

Customer Id          1.00
Age                 16.55
Income_Usd          22.00
Credit Score        18.00
Tenure_Years        12.90
Monthly_Visits      14.00
Satisfaction        19.95
City                15.00
Customer_Segment    19.00
Gender              12.00
Is_Active           17.00
Churn_Flag           8.00
Signup_Date         12.00
Lead_Source         21.00
Notes_Text          32.80
dtype: float64

#### 6. Find the rows where Customer ID is missing.

In [22]:
Missing_Customer = df[df['Customer Id'].isnull()]

Missing_Customer.index

Index([ 162,  226,  300,  421,  770,  821,  876,  993, 1023, 1188, 1202, 1212,
       1248, 1338, 1346, 1448, 1451, 1462, 1564, 1652],
      dtype='int64')

#### 7. Remove leading/trailing whitespace from all column names and convert them to lowercase with underscores.

In [25]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

#### 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [35]:
df['customer_id'].duplicated().sum()

np.int64(19)

#### 9. Remove duplicate customer records while keeping the first occurrence.

In [44]:
df.drop_duplicates(subset="customer_id", keep="first")

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673405659,28198.41033378447,660.5629175986682,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516427959453,61312.83129054326,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67123886594,613.1327753975876,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357804628894,56259.90961066413,720.2369862405794,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.641956219115,549.183252322903,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269511776246272,79436.89335323017,633.9740063023814,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505105393,39912.379910506046,701.7201056433207,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696203639,24522.265445928326,647.7993363128053,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61055756662,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.2560949072122,53723.87392391664,576.739073460913,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

#### 10.Find all unique values in the customer_segment column and identify inconsistent categories such as Consumer, consumer, consumer , etc.

In [41]:
df["customer_segment"].value_counts(dropna=False)

customer_segment
Consumer      661
SMB           390
NaN           378
Enterprise    290
consumer      118
UNKNOWN        76
SMB.           68
Name: count, dtype: int64

#### 11.Clean the customer_segment column by standardizing capitalization and whitespace.

In [54]:
import numpy as np

df["customer_segment"] = (
    df["customer_segment"]
    .str.strip()
    .str.replace(".", "", regex=False)
    .str.title()
    .replace("Unknoun", "Unknown")
)

df["customer_segment"].value_counts()

customer_segment
Consumer      779
Smb           458
Enterprise    290
Unknown        76
Name: count, dtype: int64

#### 12.Find all unique values in the gender column and convert them into consistent categories such as Male and Female.

In [58]:
df["gender"].unique()

array([nan, 'Male', 'Female'], dtype=object)

In [57]:
df["gender"] = (
    df["gender"]
    .str.strip()
    .str.lower()
    .replace({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

df["gender"].value_counts()

gender
Male      881
Female    861
Name: count, dtype: int64

#### 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0.

In [59]:
df["is_active"] = (
    df["is_active"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        "yes": 1,
        "y": 1,
        "1": 1,
        "no": 0,
        "n": 0,
        "0": 0
    })
)

df["is_active"].value_counts()

is_active
1      841
0      802
nan    338
Name: count, dtype: int64

#### 14.Convert the churn_flag column from categorical values (Yes/No) into a binary numerical column (1/0).

In [60]:
df["churn_flag"] = (
    df["churn_flag"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        "yes": 1,
        "no": 0
    })
)

df["churn_flag"].value_counts()

churn_flag
0      1383
1       441
nan     157
Name: count, dtype: int64

#### 15.Identify all values in income_usd that cannot be directly interpreted as numbers.

In [62]:
income_numeric = pd.to_numeric(df["income_usd"], errors="coerce")


invalid_income = df.loc[
    income_numeric.isna() & df["income_usd"].notna(),
    "income_usd"
].unique()

invalid_income

array(['$44,696', '$41,941', '$123,682', '$40,978', '$45,565', '$112,864',
       '$38,946', '$93,738', '$70,056', '$26,771', 'missing', '$48,959',
       '$36,410', '$86,520', '$88,847', '$88,960', '$50,211', '$104,630',
       '$72,142', '$34,864', '$130,837', '$90,730', '$29,657', '$60,407',
       '₹55k', '$506,709', '$71,214', '$191,997', '$35,341', '$171,139',
       '$65,761', '$30,152', '$47,631', '$319,924', '$46,216', '$49,366',
       '$78,703', '$44,955', '$76,860', '$50,094', '$129,799', '$32,702',
       '$33,399', '$19,760', '$146,497', '$30,746', '$107,324', '$19,808',
       'error', '$49,885', '$22,575', '$53,462', '$100,254', '$37,397',
       '$89,920', '$60,643', '$153,576', '$114,703', '$117,570',
       '$155,204', '$39,065', '$108,002', '$33,428', '$18,612', '$32,495',
       '$31,099', '$60,008', '$31,588', '$84,034', '$92,205', '$30,921',
       '$38,009', '$61,792', '$48,656', '$49,855', '$23,569', '$38,605',
       '$37,860', '$47,580', '$24,527', '$78,202', '$53,993', '$64,415',
       'not available', '$99,869', '$543,686', '$74,109', '$45,886',
       '$75,683', '$59,291', '$41,955', '$37,026', '$13,148', '$56,234',
       '$73,642', '$44,722', '$39,362', '$41,269', '$33,259', '$34,160',
       '$45,415', '$55,242', '$35,506', '$352,568', '$25,393', '$20,322',
       '$65,732', '$15,187', '$61,230', '$38,916', '$97,960', '$93,193',
       '$42,625', '$36,305', '$33,715', '$34,982', '$45,435', '$212,590',
       '$151,415', '$38,849', '$256,510', '$25,921', '$52,112',
       '$155,352', '$45,288', '$76,139', '$48,047', '$27,675', '$55,161',
       '$63,822', '$124,103', '$26,579', '$27,606', '$87,822', '$83,857',
       '$31,808', '$24,295', '$22,540', '$38,251', '$41,234', '$506,702',
       '$52,352', '$31,857', '$98,449', '$54,157', '$49,817', '$17,863',
       '$160,831', '$119,220', '$264,787', '$69,968', '$105,759',
       '$76,027', '$24,407', '$135,870', '$40,483', '$68,496', '$53,034',
       '$50,179', '$41,996', '$295,916', '$100,739', '$64,975', '$64,537',
       '$30,668', '$47,068', '$51,813', '$57,778', '$50,057', '$125,589',
       '$22,832', '$58,551', '$135,575', '$34,809', '$80,389', '$58,046'],
      dtype=object)