## Pandas Method Task

In [3]:
import pandas as pd

df = pd.read_excel("C:\\Users\\rohit\\Downloads\\Bank_customer_churn.xlsx")

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Easy Level (1–10)

#### Q1 Load the dataset and display the first 10 records.

In [4]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

#### Q2 Display the last 15 customers.

In [5]:
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Q3 Show 7 random customer records.

In [6]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1360,1361,15694409,Tsao,647,Germany,Female,22,3,97975.82,2,0,1,62083.00,0
3755,3756,15620030,Jamieson,744,France,Male,29,1,0.00,1,0,0,82422.97,0
3335,3336,15660735,T'ang,581,Spain,Female,31,6,0.00,2,1,0,188377.21,0
8088,8089,15815656,Hopkins,541,Germany,Female,39,9,100116.67,1,1,1,199808.10,1
2581,2582,15634719,Chinwendu,704,France,Male,31,0,0.00,2,1,0,183038.33,0
5872,5873,15684248,Meng,658,Spain,Male,21,7,0.00,2,0,1,154279.87,0
6590,6591,15674868,Wei,696,Spain,Female,30,0,0.00,2,1,1,9002.80,0

#### Q4 Print complete dataset information and identify:
##### • Total columns
##### • Data type of each column
##### • Missing values

In [10]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

#### Q5 Find missing values in every column.

In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

#### Q6 Display only numerical columns.

In [18]:
int_column = df.select_dtypes(include = ["int"]).columns
int_column

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

#### Q7 Generate the statistical summary of numerical columns.

In [17]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

#### Q8 Find duplicate rows and print how many exist.

In [16]:
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

#### Q9 Remove duplicate rows and store the cleaned dataset.

In [12]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_cleaned.shape)
print("Number of duplicate rows removed:", df.shape[0] - df_cleaned.shape[0])

Original shape: (10000, 14)
Cleaned shape: (10000, 14)
Number of duplicate rows removed: 0

#### Q10 Count how many customers have exited and how many have not exited.

In [15]:
exit_counts = df['Exited'].value_counts()
exit_counts

Exited
0    7963
1    2037
Name: count, dtype: int64

## Medium Level (11–20)

#### Q11 Rename the following columns:
#### CustomerId → Customer_ID
#### CreditScore → Credit_Score
#### EstimatedSalary → Salary
#### Exited → Churn

In [19]:
df.rename(columns={
    'CustomerId': 'Customer_ID',
    'CreditScore': 'Credit_Score',
    'EstimatedSalary': 'Salary',
    'Exited': 'Churn'
}, inplace=True)

df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Churn'],
      dtype='object')

#### Q12 Add the prefix
#### Bank_
#### to every column name.

In [20]:
df = df.add_prefix('Bank_')

df.columns

Index(['Bank_RowNumber', 'Bank_Customer_ID', 'Bank_Surname',
       'Bank_Credit_Score', 'Bank_Geography', 'Bank_Gender', 'Bank_Age',
       'Bank_Tenure', 'Bank_Balance', 'Bank_NumOfProducts', 'Bank_HasCrCard',
       'Bank_IsActiveMember', 'Bank_Salary', 'Bank_Churn'],
      dtype='object')

#### Q13 Convert the Age column into float datatype.

In [21]:
df['Bank_Age'] = df['Bank_Age'].astype(float)

df['Bank_Age'].dtype

dtype('float64')

#### Q14 Convert the Exited column into string datatype.

In [22]:
df['Bank_Churn'] = df['Bank_Churn'].astype(str)

df['Bank_Churn'].dtype

dtype('O')

#### Q15 Suppose the Balance column has missing values.
####     Replace them using the mean of the Balance column.

In [23]:
df['Bank_Balance'] = df['Bank_Balance'].fillna(df['Bank_Balance'].mean())

df['Bank_Balance'].isnull().sum()

np.int64(0)